### ISSUE TITLE
Tweak highlight range

### ISSUE THREAD

**Issue by koic** [ruby/error_highlight#17]
It seems to be clearer if the highlight range will be tweaked to the method name. Currently it contains dot.

## Expected

```
1.time {}
  ^^^^
Did you mean?  times
```

## Actual

```
1.time {}
 ^^^^^
Did you mean?  times
```

**Comment by mame** [comment]
I intentionally designed the current behavior to make it clear that it is a method call syntax, but I'm not sure which is better. Does anyone have an opinion?

**Comment by mame** [comment]
I would like to close this as I have not received any similar reports. I may reconsider if the underline turns out to be uncomfortable or obviously consufing to many people.
