### ISSUE TITLE
How about "known issues" document?

### ISSUE THREAD

**Issue by pocke** [ruby/error_highlight#3]
This gem has known issues, so I think it is more helpful if a known issue document exists.

I know the following issues:

* shift `^^^` with multibyte characters
* comment and backslash ref: #2
* IRB doesn't highlight

**Comment by mame** [comment]
Looks good. Where should we put such a document? Wiki, `known_issues.md`, or `doc/` directory?

**Comment by ttanimichi** [comment]
The bottom of the README would be a good place

**Comment by pocke** [comment]
I think the README must have links to the known issues at least, but the details should be another place to keep the README short.
I think GitHub Issue will be a good place, because we manage issues with GitHub Issue. It will avoid managing the same things in two places.

**Comment by mame** [comment]
I've created #4, #5 and #6
