### ISSUE TITLE
NameError column adjustment

### ISSUE THREAD

**Issue by ksss** [ruby/error_highlight#31]
If there is no top-level const, the behavior is currently as follows

```
$ ruby -e 'Foo::Bar::Baz.new'
-e:1:in `<main>': uninitialized constant Foo (NameError)

Foo::Bar::Baz.new
        ^^^^^
```

Shouldn't it behave as follows?

```
$ ruby -e 'Foo::Bar::Baz.new'
-e:1:in `<main>': uninitialized constant Foo (NameError)

Foo::Bar::Baz.new
^^^
```

**Comment by mame** [comment]
Thank you for the report. This is caused by an optimization of RubyVM compiler: https://github.com/ruby/ruby/pull/6187 . I'll see what I can do to help.

**Comment by ksss** [comment]
Thanks!
