### ISSUE TITLE
Fails in Github Actions in Ruby 3.1.4

### ISSUE THREAD

**Issue by andykimchris** [ruby/error_highlight#39]
You have already activated error_highlight 0.3.0, but your Gemfile requires error_highlight 0.5.1. Since error_highlight is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports error_highlight as a default gem. (Gem::LoadError).

Running Ruby 3.1.4, Rails 7.1.1

**Comment by mame** [comment]
I have no idea. You may want to ask it to those who are familiar with bundler in https://github.com/rubygems/rubygems.

**Comment by Frexuz** [comment]
Same here :( Same ruby/rails versions

**Comment by simi** [comment]
@andykimchris please can you share link to failing action or share steps to reproduce?

**Comment by andykimchris** [comment]
@simi Here. It's failing with both jobs. Simple checks on db setup and security audits.
 
   name: Rails Backend CI/CD V1
  
    on:
      push:
        branches:
          - "*"
    
      pull_request:
        branches:
          - develop
  
    jobs:
      test:
        name: Rspec Test Environment
        runs-on: ubuntu-latest
    
        services:
          postgres:
            image: postgres:latest
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: password
              # POSTGRES_DB: inicro_testing
            ports:
              - 5432:5432
            options: --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Install Ruby and gems
            uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
            with:
              bundler-cache: true
              ruby-version: 3.1.4
    
          - name: Install dependencies
            run: |
              gem install bundler
              bundle install --jobs 4 --retry 3
          - name: Install system dependencies
            run: |
              sudo apt-get -y update
          - name: Install PostgreSQL client
            run: |
              sudo apt-get -yqq install libpq-dev
          - name: Start PostgreSQL service
            run: |
              sudo service postgresql restart
          - name: Database setup
            env:
              INICRO_USER: postgres
              INICRO_PASSWORD: password
              RAILS_ENV: test
              RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
            run: |
              bundle exec rails db:test:prepare db:migrate RAILS_ENV=test
          - name: RSpec tests
            env:
              INICRO_USER: postgres
              INICRO_PASSWORD: password
              RAILS_ENV: test
              RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
            run: |
              bundle exec rspec
          - name: Create code coverage report
            uses: actions/upload-artifact@v2
            with:
              name: code-coverage
              path: coverage/
    
      lint:
        name: Linting and Security Audit
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Set up Ruby
            uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
            with:
              bundler-cache: true
              ruby-version: 3.1.4
    
          - name: Install dependencies
            run: |
              gem install bundler
              bundle install --jobs 4 --retry 3
          - name: Security audit dependencies
            run: bundle exec bundler-audit --update
    
          - name: Security audit application code
            run: bundle exec brakeman -q -w2
    
          - name: Lint via RuboCop
            run: bundle exec rubocop --parallel -A`

**Comment by simi** [comment]
@andykimchris can you share the output of the job (at least partially)?

**Comment by andykimchris** [comment]
![image](https://github.com/ruby/error_highlight/assets/26143161/ee801224-97b6-412f-8bef-8c783e5327b3)

![image](https://github.com/ruby/error_highlight/assets/26143161/00afdfbe-7d44-4b14-9c36-d791deb9385c)

Here are 2 screenshots for both jobs. Check the actions they're failing at.

**Comment by kbrock** [comment]
I think you can fix this locally using:
```
gem update --system
```

And I think you can fix in your action using:

```yaml
      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
          ruby-version: 3.1.4
          rubygems: latest
```

I'm still figuring this stuff out locally but the versions of the default gems (the gems brought into ruby.exe directories) change across ruby versions. (e.g. see https://stdgems.org/3.0.4/ ). Heck, the actual list of gems that come with the ruby versions change.


For ruby 2.7 I used this to update time/cgi/uri gems (they had CVEs)

**Comment by andykimchris** [comment]
Unfortunately, this doesn't fix the issue. I've even tried with different versions of setup-ruby action. The obvious band-aid fix is simply to remove the gem, but I don't want to go down that path.

**Comment by andykimchris** [comment]
So this issue is primarily in Ruby 3.1.4. Switching to Ruby 3.2.2 solves it. I won't move further along with this, but someone else is free to open it up if they can figure out the issue with the version.

**Comment by kg-currenxie** [comment]
thx, switching to 3.2.2 worked for me 👌
