### ISSUE TITLE
Handle very long line well

### ISSUE THREAD

**Issue by mame** [ruby/error_highlight#5]
```
$ ruby t.rb
t.rb:1:in `<main>': undefined method `gsuub' for "fooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooooooooooooooooooooooo":S
tring (NoMethodError)

"foooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
oo".gsuub(//, "")


   ^^^^^^
Did you mean?  gsub
```

Should we truncate such a long code snippet to fit it with the width of terminal?

**Comment by ioquatix** [comment]
![image](https://user-images.githubusercontent.com/30030/221718584-5f73a5b5-3d8d-4f26-a719-a7b53cae25d3.png)

This might be another argument for using bold or xterm color in addition or alternatively to `^^^` style.

**Comment by karreiro** [comment]
> Should we truncate such a long code snippet to fit it with the width of terminal?

Hey @mame, I share the same understanding, and I believe that’s a good idea (I’ve noticed other similar tools adopting the same approach). I’ve left a proposal here: https://github.com/ruby/error_highlight/pull/51
